package org.example.learniversebe.enums;

public enum NotificationType {
    COMMENT,
    REPLY,
    MENTION,
    LIKE,
    BOOKMARK,
    FRIEND_REQUEST,
    FRIEND_ACCEPT,
    GROUP_INVITE,
    GROUP_JOIN_ACCEPT,
    POST_SHARE,
    REPORT,
    ANSWER,
    ANSWER_ACCEPTED,
    VOTE,
    SYSTEM,
    BROADCAST,
    CONTENT_DELETED,
    WARNING_RECEIVED,
    ACCOUNT_SUSPENDED,
    ACCOUNT_BANNED,
    REPORT_RESOLVED,
    CONTENT_AUTO_FLAGGED,
    CONTENT_RESTORED
}

